#!/bin/bash

echo "Google Maps API Key Configuration Helper"
echo "========================================"
echo ""
echo "Your app details:"
echo "Package Name: com.yabalash.orderv2"
echo "Debug SHA-1: 2A:B4:05:15:46:AB:92:DB:7F:56:98:43:1C:F6:56:56:00:F7:4C:DA"
echo "API Key: AIzaSyB85kLYYOmuAhBUPd7odVmL6gnQsSGWU-4"
echo ""
echo "Steps to fix the Google Maps authorization error:"
echo ""
echo "1. Open Google Cloud Console:"
echo "   https://console.cloud.google.com/"
echo ""
echo "2. Go to APIs & Services > Credentials"
echo ""
echo "3. Click on your API key (AIzaSyB85kLYYOmuAhBUPd7odVmL6gnQsSGWU-4)"
echo ""
echo "4. Under 'Application restrictions', select 'Android apps'"
echo ""
echo "5. Click 'Add an item' and enter:"
echo "   - Package name: com.yabalash.orderv2"
echo "   - SHA-1 fingerprint: 2A:B4:05:15:46:AB:92:DB:7F:56:98:43:1C:F6:56:56:00:F7:4C:DA"
echo ""
echo "6. Save the changes"
echo ""
echo "7. Make sure 'Maps SDK for Android' is enabled in APIs & Services > Library"
echo ""
echo "8. Wait 5 minutes for changes to propagate"
echo ""
echo "9. Clean and rebuild the Flutter app:"
echo "   flutter clean"
echo "   flutter pub get"
echo "   flutter run"
echo ""
echo "For iOS, also add iOS bundle restrictions if needed."
echo ""
echo "Press any key to continue..."
read -n 1